// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var $$String = require("bs-platform/lib/js/string.js");
var Caml_string = require("bs-platform/lib/js/caml_string.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("PokemonCard");

function make(name, url, _children) {
  var getPokeId = function (text) {
    return $$String.make(1, Caml_string.get(text, $$String.rindex(text, /* "/" */47) - 1 | 0));
  };
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              var pokeId = getPokeId(url);
              toDataURL("https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/" + (String(pokeId) + ".png"), (function (base64Str) {
                      return Curry._1(self[/* send */3], /* SetImageBase64 */[
                                  false,
                                  base64Str
                                ]);
                    }));
              toDataURL("https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/" + (String(pokeId) + ".png"), (function (base64Str) {
                      return Curry._1(self[/* send */3], /* SetImageBase64 */[
                                  true,
                                  base64Str
                                ]);
                    }));
              var intervalId = setInterval((function (param) {
                      return Curry._1(self[/* send */3], /* ChangeImage */0);
                    }), 1000);
              return Curry._1(self[/* onUnmount */4], (function (param) {
                            clearInterval(intervalId);
                            return /* () */0;
                          }));
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", {
                          className: "col-sm-6 mb-3"
                        }, React.createElement("div", {
                              className: "card"
                            }, React.createElement("div", {
                                  className: "row no-gutters"
                                }, React.createElement("div", {
                                      className: "col-md-4"
                                    }, React.createElement("img", {
                                          className: "card-img",
                                          alt: name,
                                          src: self[/* state */1][/* imageStr */2]
                                        })), React.createElement("div", {
                                      className: "col-md-8"
                                    }, React.createElement("div", {
                                          className: "card-body"
                                        }, React.createElement("h5", {
                                              className: "card-title"
                                            }, name), React.createElement("p", {
                                              className: "card-text"
                                            }, url))))));
            }),
          /* initialState */(function (param) {
              return /* record */[
                      /* pokeId */getPokeId(url),
                      /* shiny */false,
                      /* imageStr */"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/0.png",
                      /* shinyBase64 */"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/0.png",
                      /* base64 */"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/0.png"
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (action) {
                var resultStr = action[1];
                if (action[0]) {
                  return /* Update */Block.__(0, [/* record */[
                              /* pokeId */state[/* pokeId */0],
                              /* shiny */state[/* shiny */1],
                              /* imageStr */state[/* imageStr */2],
                              /* shinyBase64 */resultStr,
                              /* base64 */state[/* base64 */4]
                            ]]);
                } else {
                  return /* Update */Block.__(0, [/* record */[
                              /* pokeId */state[/* pokeId */0],
                              /* shiny */state[/* shiny */1],
                              /* imageStr */state[/* imageStr */2],
                              /* shinyBase64 */state[/* shinyBase64 */3],
                              /* base64 */resultStr
                            ]]);
                }
              } else if (state[/* shiny */1]) {
                return /* Update */Block.__(0, [/* record */[
                            /* pokeId */state[/* pokeId */0],
                            /* shiny */!state[/* shiny */1],
                            /* imageStr */state[/* shinyBase64 */3],
                            /* shinyBase64 */state[/* shinyBase64 */3],
                            /* base64 */state[/* base64 */4]
                          ]]);
              } else {
                return /* Update */Block.__(0, [/* record */[
                            /* pokeId */state[/* pokeId */0],
                            /* shiny */!state[/* shiny */1],
                            /* imageStr */state[/* base64 */4],
                            /* shinyBase64 */state[/* shinyBase64 */3],
                            /* base64 */state[/* base64 */4]
                          ]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
