// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var $$String = require("bs-platform/lib/js/string.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var SearchBar$ReactTemplate = require("./components/SearchBar.bs.js");
var PokemonCard$ReactTemplate = require("./components/PokemonCard.bs.js");

function contains(s1, s2) {
  try {
    var len = s2.length;
    for(var i = 0 ,i_finish = s1.length - len | 0; i <= i_finish; ++i){
      if ($$String.sub(s1, i, len) === s2) {
        throw Pervasives.Exit;
      }
      
    }
    return false;
  }
  catch (exn){
    if (exn === Pervasives.Exit) {
      return true;
    } else {
      throw exn;
    }
  }
}

var component = ReasonReact.reducerComponent("App");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              return Curry._1(self[/* send */3], /* FilterUsing */Block.__(1, [""]));
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var pokeList = List.mapi((function (i, pokemon) {
                      return ReasonReact.element(String(i), undefined, PokemonCard$ReactTemplate.make(pokemon[/* name */0], pokemon[/* url */1], /* array */[]));
                    }), self[/* state */1][/* pokemonsFiltered */2]);
              return React.createElement("div", {
                          className: "main-app"
                        }, ReasonReact.element(undefined, undefined, SearchBar$ReactTemplate.make(self[/* state */1][/* searchText */0], (function (searchText) {
                                    var searchText$1 = searchText;
                                    Curry._1(self[/* send */3], /* OnSearch */Block.__(0, [searchText$1]));
                                    return Curry._1(self[/* send */3], /* FilterUsing */Block.__(1, [searchText$1]));
                                  }), /* array */[])), React.createElement("div", {
                              className: "pokemon-list"
                            }, React.createElement("div", {
                                  className: "row"
                                }, $$Array.of_list(pokeList))));
            }),
          /* initialState */(function (param) {
              return /* record */[
                      /* searchText */"",
                      /* pokemons : :: */[
                        /* record */[
                          /* name */"bulbasaur",
                          /* url */"https://pokeapi.co/api/v2/pokemon/1/"
                        ],
                        /* :: */[
                          /* record */[
                            /* name */"ivysaur",
                            /* url */"https://pokeapi.co/api/v2/pokemon/2/"
                          ],
                          /* :: */[
                            /* record */[
                              /* name */"venusaur",
                              /* url */"https://pokeapi.co/api/v2/pokemon/3/"
                            ],
                            /* :: */[
                              /* record */[
                                /* name */"charmander",
                                /* url */"https://pokeapi.co/api/v2/pokemon/4/"
                              ],
                              /* :: */[
                                /* record */[
                                  /* name */"charmeleon",
                                  /* url */"https://pokeapi.co/api/v2/pokemon/5/"
                                ],
                                /* :: */[
                                  /* record */[
                                    /* name */"charizard",
                                    /* url */"https://pokeapi.co/api/v2/pokemon/6/"
                                  ],
                                  /* [] */0
                                ]
                              ]
                            ]
                          ]
                        ]
                      ],
                      /* pokemonsFiltered : [] */0
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (action.tag) {
                var searchText = action[0];
                var pokemonsFiltered = List.filter((function (pokemon) {
                          return contains(pokemon[/* name */0], searchText);
                        }))(state[/* pokemons */1]);
                return /* Update */Block.__(0, [/* record */[
                            /* searchText */searchText,
                            /* pokemons */state[/* pokemons */1],
                            /* pokemonsFiltered */pokemonsFiltered
                          ]]);
              } else {
                return /* Update */Block.__(0, [/* record */[
                            /* searchText */action[0],
                            /* pokemons */state[/* pokemons */1],
                            /* pokemonsFiltered */state[/* pokemonsFiltered */2]
                          ]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var App = /* module */[
  /* component */component,
  /* make */make
];

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, make(/* array */[])), "app");

exports.contains = contains;
exports.App = App;
/* component Not a pure module */
